version: '3.3'

services:


    api_student_age:
        container_name: api_student_age
        volumes:
            - ./simple_api/:/data
        networks:
            - appnet
        image: api_student_age
        ports:
            - "5000:5000"




    frontend_student_age:
        container_name: frontend_student_age
        volumes:
            - ./website/:/var/www/html
        environment:
            - USERNAME=toto
            - PASSWORD=python
        networks:
            - appnet
        depends_on:
            - api_student_age
        image: php:apache
        ports:
            - "80:80"



networks:
    appnet:
        external: true
        name: appnet
